### ISSUE TITLE
Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [Invertex/BinaryFilePatcher#1]
Dear @Invertex,
Could you be so kind to generate ```.exe``` for the rest of us who are mere Windows users w/o compiler?

**Comment by Invertex** [comment]
https://github.com/Invertex/BinaryFilePatcher/releases/tag/Releases

**Comment by sergeevabc** [comment]
@Invertex, thank you for taking the time to make your program more accessible to the general public by compiling an executable. Unfortunately, it is hard to use it without reading the instructions first as plain launch outputs nothing.

``` console
$ BinaryFilePatcher.exe
```
